- name: Copy config to /tmp
  template:
    src: ../templates/config.xml
    dest: /tmp/config.xml

- name: Upload PAN config
  panos_import:
    ip_address: 172.16.1.1
    password: "admin"
    file: /tmp/config.xml
    category: "configuration"
    validate_certs: no
  register: upload_result

- name: Load configuration
  panos_loadcfg:
    ip_address: 172.16.1.1
    password: "admin"
    file: "{{upload_result.filename}}"
  environment:
    PYTHONHTTPSVERIFY: 0
  async: 1
  poll: 0
