- name: Try to reach PAN
  panos_check:
    ip_address: "172.16.1.{{ team_number }}"
    password: "admin"
  register: auth_check
  ignore_errors: yes

- name: Copy config to /tmp
  template:
    src: ../templates/config.xml
    dest: /tmp/config.xml
  when: auth_check is not failed

- name: Upload PAN config
  panos_import:
    ip_address: "172.16.1.{{ team_number }}"
    password: "admin"
    file: /tmp/config.xml
    category: "configuration"
  register: upload_result
  when: auth_check is not failed

- name: Load configuration
  panos_loadcfg:
    ip_address: "172.16.1.{{ team_number }}"
    password: "admin"
    file: "{{upload_result.filename}}"
  environment:
    PYTHONHTTPSVERIFY: 0
  async: 1
  poll: 0
  when: auth_check is not failed

- name: Delete config from /tmp
  file:
    path: /tmp/config.xml
    state: absent
  when: auth_check is not failed
