- name: Point DNS at domain controller
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
      - 10.1.4.10

- name: Rename hostname
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_reboot

- name: Reboot host if necessary
  win_reboot:
  when: hostname_reboot.reboot_required == true

- name: Join host to domain
  win_domain_membership:
    dns_domain_name: team4.wildeagle.local
    hostname: "{{ lookup('csvfile', '{{ ansible_ip_addresses[0] }} file=../../tintin/files/hostnames.csv delimiter=,') }}"
    domain_admin_user: TEAM4\Administrator
    domain_admin_password: Change.me!
    state: domain
  register: domain_state

- name: Reboot if necessary
  win_reboot:
  when: domain_state.reboot_required

- name: Enable Remote Desktop
  raw: Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0 -Force

- name: Disable firewall
  win_firewall:
    state: disabled
    profiles:
      - Public
      - Private
      - Domain

- name: Disable Windows Defender
  raw: Set-MpPreference -DisableRealtimeMonitoring $true
