- name: Set the hostname
  hostname:
    name: "{{ ansible_host }}"

- name: Transfer hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Disable SELinux
  selinux:
    state: disabled
  notify: 
    - Reboot
    - Wait for reboot
  when: ansible_os_family == 'RedHat'

- name: Stop the firewall (CentOS firewalld)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == 'RedHat'

- name: Forward syslog to Splunk
  lineinfile:
    path: '/etc/rsyslog.conf'
    line: '*.* @@10.10{{team_number}}.0.103:514'
    insertbefore: '# ### end of the forwarding rule ###'
  notify:
    - Restart rsyslog

- name: Add scoringeEngine user with scoringEngineTest password
  user:
    name: scoringEngine
    password: $6$saltOnMySteak$lF/lqv8Ym7Zeciz66mAkr216N6TNb/WOWxTSDvHld8taptFVg4UMQf6hMUvHGG5oNqxYErunBFGMy3YTAApJV.
    state: present