- name: Set the hostname
  hostname:
    name: "{{ ansible_host }}"

- name: Disable SELinux
  selinux:
    state: disabled
  notify: 
    - Reboot
    - Wait for reboot

- name: Stop the firewall
  service:
    name: firewalld
    state: stopped
    enabled: no
