- name: Set the hostname
  hostname:
    name: "{{ ansible_host }}"

- name: Transfer hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Disable SELinux
  selinux:
    state: disabled
  notify: 
    - Reboot
    - Wait for reboot

- name: Stop the firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Forward syslog to Splunk
  lineinfile:
    path: '/etc/rsyslog.conf'
    line: '*.* @@10.0.0.103:514'
    insertbefore: '# ### end of the forwarding rule ###'
  notify:
    - Restart rsyslog