- name: Install MariaDB and database packages
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - mariadb-server
    - mysql
    - MySQL-python # Needed for MySQL Ansible modules

- name: Add OTRS MariaDB config
  copy:
    src: zotrs.conf
    dest: /etc/my.cnf.d/zotrs.cnf
  notify: Restart MariaDB

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Add OTRS database and import initial data
  mysql_db:
    name: otrs
    encoding: utf8
    state: present
  notify:
    - Copy OTRS DB Dump
    - Import OTRS DB
    - Remove OTRS DB Dump

- name: Add OTRS User with full privs on OTRS DB
  mysql_user:
    name: otrs
    password: "{{ common_password }}"
    priv: 'otrs.*:ALL'
    state: present

- name: Get OTRS RPM
  get_url:
    url: http://ftp.otrs.org/pub/otrs/RPMS/rhel/7/otrs-6.0.7-01.noarch.rpm
    dest: /tmp/otrs.rpm

- name: Install OTRS
  yum:
    name: /tmp/otrs.rpm
    disable_gpg_check: yes
    state: present

- name: Install OTRS required Perl modules
  yum:
    name: "perl(Text::CSV_XS)"
    state: present

- name: Add OTRS config
  template:
    src: Config.pm
    dest: /opt/otrs/Kernel/Config.pm

- name: Start OTRS
  shell: /opt/otrs/bin/otrs.Daemon.pl start
  become: yes
  become_user: otrs

- name: Start OTRS Cron daemon
  shell: /opt/otrs/bin/Cron.sh start
  become: yes
  become_user: otrs

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes
