- name: Disable SELinux
  selinux:
    state: disabled

- name: Stop the firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Set file descriptor limits frequired by GLUU
  blockinfile:
    path: /etc/security/limits.conf
    insertbefore: '# End of file'
    block: |
      soft nofile 65536
      hard nofile 262144

- name: Add Gluu repo
  copy:
    src: Gluu-centos7.repo
    dest: /etc/yum.repos.d/Gluu-centos7.repo

- name: Install Gluu
  yum:
    pkg: gluu-server-3.1.3
    state: present