- name: Install Active Directory
  win_feature:
    name: AD-Domain-Services
    include_management_tools: True
    state: present
  register: ad_result

- name: Reboot server if required
  win_reboot:
  when: ad_result.reboot_required

- name: Ensure domain exists
  win_domain:
     dns_domain_name: team4.wildeagle.local
     safe_mode_password: Change.me!
  register: domain_result

- name: Reboot server if required
  win_reboot:
  when: domain_result.reboot_required

- name: Promote to domain controller
  win_domain_controller:
     dns_domain_name: team4.wildeagle.local
     domain_admin_user: Administrator@wildeagle.local
     domain_admin_password: Change.me!
     safe_mode_password: Change.me!
     state: domain_controller
  register: ad_result

- name: Reboot server if required
  win_reboot:
  when: ad_result.reboot_required

- name: See if DNS already imported
  win_shell: nslookup gadget.team4.wildeagle.local
  register: dns_output

- name: Upload DNS records
  win_copy:
     src: ../files/hostnames.csv
     dest: C:\hostnames.csv
  when: dns_output.stderr.find("can't find") != -1

- name: Import DNS records
  script: ../files/Import-DNS.ps1 C:\hostnames.csv
  when: dns_output.stderr.find("can't find") != -1

- name: Clean up DNS records
  win_file:
     path: C:\hostnames.csv
     state: absent
  when: dns_output.stderr.find("can't find") != -1

- name: Add DNS forwarder
  win_shell: Add-DnsServerForwarder -IPAddress 10.1.4.254

# Return code on this command is non-zero if sam isn't in this domain, so
# ignore errors on this task

- name: See if users already imported
  win_shell: net user sam /domain
  register: user_output
  ignore_errors: yes

- name: Disable password complexity
  win_security_policy:
     section: System Access
     key: PasswordComplexity
     value: 0

- name: Upload usernames
  win_copy:
     src: ../files/users.csv
     dest: C:\users.csv
  when: user_output.rc != 0

- name: Import domain users
  script: ../files/Add-Users.ps1 C:\users.csv
  when: user_output.rc != 0

- name: Clean up users.csv
  win_file:
     path: C:\users.csv
     state: absent
  when: user_output.rc != 0
