- name: Install Active Directory
  win_feature:
    name: AD-Domain-Services
    include_management_tools: True
    state: present
  register: ad_result

- name: Reboot server if AD was installed
  win_reboot:
  when: ad_result.reboot_required

- name: Ensure domain exists
  win_domain:
     dns_domain_name: team4.wildeagle.local
     safe_mode_password: Change.me!
  register: domain_result

- name: Reboot server if domain is created
  win_reboot:
  when: domain_result.reboot_required

- name: Promote to domain controller
  win_domain_controller:
     dns_domain_name: team4.wildeagle.local
     domain_admin_user: Administrator@wildeagle.local
     domain_admin_password: Change.me!
     safe_mode_password: Change.me!
     state: domain_controller
  register: ad_result

- name: Reboot server again
  win_reboot:
  when: ad_result.reboot_required

- name: Upload DNS records
  win_copy:
     src: ../files/hostnames.csv
     dest: C:\hostnames.csv

- name: Import DNS records
  script: ../files/Import-DNS.ps1 C:\hostnames.csv

- name: Clean up DNS records
  win_file:
     path: C:\hostnames.csv
     state: absent

- name: Upload usernames
  win_copy:
     src: ../files/users.csv
     dest: C:\users.csv

- name: Import domain users
  script: ../files/Add-Users.ps1 C:\users.csv

- name: Clean up users.csv
  win_file:
     path: C:\users.csv
     state: absent
