- name: Rename hostname
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_reboot

- name: Reboot host if necessary
  win_reboot:
  when: hostname_reboot.reboot_required == true

- name: Install Active Directory
  win_feature:
    name: AD-Domain-Services
    include_management_tools: True
    state: present
  register: ad_result

- name: Reboot server if required
  win_reboot:
  when: ad_result.reboot_required

- name: Ensure domain exists
  win_domain:
     dns_domain_name: team4.wildeagle.local
     safe_mode_password: Change.me!
  register: domain_result

- name: Reboot server if required
  win_reboot:
  when: domain_result.reboot_required

- name: Promote to domain controller
  win_domain_controller:
     dns_domain_name: "team{{ team_number }}.wildeagle.local"
     domain_admin_user: "Administrator@team{{ team_number }}.wildeagle.local"
     domain_admin_password: Change.me!
     safe_mode_password: Change.me!
     state: domain_controller
  register: ad_result

- name: Reboot server if required
  win_reboot:
  when: ad_result.reboot_required

- name: See if DNS already imported
  win_shell: nslookup gadget.team{{ team_number }}.wildeagle.local
  register: dns_output

- name: Create DNS records template file
  template:
    src: ../templates/hostnames.csv
    dest: /tmp/hostnames.csv
  delegate_to: localhost

- name: Upload DNS records
  win_copy:
     src: /tmp/hostnames.csv
     dest: C:\hostnames.csv
  when: dns_output.stderr.find("can't find") != -1

- name: Import DNS records
  script: ../files/Import-DNS.ps1 C:\hostnames.csv
  when: dns_output.stderr.find("can't find") != -1

- name: Clean up DNS records (remotely)
  win_file:
     path: C:\hostnames.csv
     state: absent
  when: dns_output.stderr.find("can't find") != -1

- name: Clean up DNS records (locally)
  file:
    path: /tmp/hostnames.csv
    state: absent

- name: Add DNS forwarder
  win_shell: Add-DnsServerForwarder -IPAddress 10.1.4.254

- name: Disable password complexity
  win_security_policy:
     section: System Access
     key: PasswordComplexity
     value: 0

- name: Upload usernames
  win_copy:
     src: ../files/users.csv
     dest: C:\users.csv

- name: Import domain users
  script: ../files/Add-Users.ps1 C:\users.csv

- name: Clean up users.csv
  win_file:
     path: C:\users.csv
     state: absent

- name: Set Administrator password to never expire
  win_domain_user:
    name: Administrator
    password_never_expires: yes
