- name: Copy config to /tmp
  copy:
    src: ../files/config.xml
    dest: /tmp/config.xml

- name: Upload PAN config
  panos_import:
    ip_address: 172.16.2.252
    password: "admin"
    file: /tmp/config.xml
    category: "configuration"
  environment:
    PYTHONHTTPSVERIFY: 0
  register: upload_result

- name: Load configuration
  panos_loadcfg:
    ip_address: 172.16.2.252
    password: "admin"
    file: "{{upload_result.filename}}"
  environment:
    PYTHONHTTPSVERIFY: 0

- name: Delete config from /tmp
  file:
    path: /tmp/config.xml
    state: absent
