- name: Set hostname
  hostname:
    name: mason.wildeagle.net
  register: hostname

- name: Reboot if hostname updated
  shell: 'sleep 1 && reboot && sleep 1'
  async: 1
  poll: 0
  when: hostname is changed

- name: Wait for server to restart
  local_action:
    module: wait_for
      host=mason
      port=22
      delay=1
      timeout=30
  when: hostname is changed

- name: Disable SELinux
  selinux:
    state: disabled

- name: Download iRedMail package
  get_url:
    url: https://bitbucket.org/zhb/iredmail/downloads/iRedMail-0.9.8.tar.bz2
    dest: /tmp/iRedMail-0.9.8.tar.bz2

- name: Extract archive
  unarchive:
    src: /tmp/iRedMail-0.9.8.tar.bz2
    dest: /tmp/iRedMail
    remote_src: yes
