- name: Set hostname
  hostname:
    name: mason.team4.wildeagle.net
  register: hostname

- name: Reboot if hostname updated
  shell: 'sleep 1 && reboot && sleep 1'
  async: 1
  poll: 0
  when: hostname is changed

- name: Wait for server to restart
  local_action:
    module: wait_for
      host=mason
      port=22
      delay=1
      timeout=30
  when: hostname is changed

- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux

- name: Reboot if SELinux state changed
  shell: 'sleep 1 && reboot && sleep 1'
  async: 1
  poll: 0
  when: selinux is changed

- name: Wait for server to restart
  local_action:
    module: wait_for
      host=mason
      port=22
      delay=1
      timeout=30
  when: hostname is changed

- name: Download iRedMail package
  get_url:
    url: https://bitbucket.org/zhb/iredmail/downloads/iRedMail-0.9.8.tar.bz2
    dest: /tmp/iRedMail-0.9.8.tar.bz2

- name: Make sure bzip2 is installed
  yum: name=bzip2 state=installed

- name: Extract archive
  unarchive:
    src: /tmp/iRedMail-0.9.8.tar.bz2
    dest: /tmp
    remote_src: yes

- name: Copy install config
  copy:
    src: ../files/config
    dest: /tmp/iRedMail-0.9.8/config
    mode: 0644

- name: Set permissions on install script
  file:
    path: "/tmp/iRedMail-0.9.8/iRedMail.sh"
    mode: 0700

- name: Install iRedMail
  shell: "IREDMAIL_DEBUG='NO' AUTO_USE_EXISTING_CONFIG_FILE=y AUTO_INSTALL_WITHOUT_CONFIRM=y bash iRedMail.sh"
  args:
    chdir: "/tmp/iRedMail-0.9.8"
  register: iredmail_install

- name: Reboot server so all iRedMail services come up
  shell: 'sleep 1 && reboot && sleep 1'
  async: 1
  poll: 0
  when: iredmail_install.rc == 0
