- name: Join host to domain
  win_domain_membership:
     dns_domain_name: team4.wildeagle.local
     hostname: {{ hostname }}
     domain_admin_user: Administrator
     domain_admin_password: Change.me!
     state: domain
  register: domain_state

- name: Reboot if necessary
  win_reboot:
  when: domain_state.reboot_required
