- name: Reboot
  win_shell: Restart-Computer
  listen: "restart Windows"

- name: Wait for reboot
  local_action:
     module: wait_for host={{ inventory_hostname }} port=5985 state=started delay=30 timeout=60
