- name: Install bind
  package:
    name: bind
    state: present

- name: Copy configuration file
  copy:
    src: ../files/named.conf
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640

- name: Copy client zone file
  copy:
    src: ../files/team4.wildeagle.net
    dest: /var/named/team4.wildeagle.net
    owner: root
    group: named
    mode: 0640

- name: Copy ansible zone file
  copy:
    src: ../files/team4.wildeagle.net.ansible
    dest: /var/named/team4.wildeagle.net.ansible
    owner: root
    group: named
    mode: 0640

- name: Restart and enable named
  systemd:
    name: named
    state: reloaded
    enabled: yes
