- name: Install bind
  package:
    name: bind
    state: present

- name: Template configuration file
  template:
    src: ../templates/named.conf
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640

- name: Template client zone file
  template:
    src: ../templates/team.wildeagle.net
    dest: /var/named/team{{item}}.wildeagle.net
    owner: root
    group: named
    mode: 0640
  loop: "{{ range (1, total_teams+1)|list }}"

- name: Copy ansible zone file
  template:
    src: ../templates/team.wildeagle.net.ansible
    dest: /var/named/team{{item}}.wildeagle.net.ansible
    owner: root
    group: named
    mode: 0640
  loop: "{{ range (1, total_teams+1)|list }}"

- name: Restart and enable named
  systemd:
    name: named
    state: reloaded
    enabled: yes
