- name: Install FTP server
  package:
    name: vsftpd
    state: present

- name: Start and enable FTP server
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: Remove default for anonymous login
  lineinfile:
    line: anonymous_enable=NO
    path: /etc/vsftpd.conf
    state: absent
  notify: Restart vsftpd

- name: Enable anonymous login
  lineinfile:
    line: anonymous_enable=YES
    path: /etc/vsftpd.conf
    state: present
  notify: Restart vsftpd

- name: Specify anonymous FTP directory
  lineinfile:
    line: anon_root=/var/ftp
    path: /etc/vsftpd.conf
    state: present
  notify: Restart vsftpd

- name: Fix PAM module, allowing local login
  lineinfile:
    regexp: 'pam_service_name=vsftpd'
    line: pam_service_name=ftp
    state: present
  notify: restart vsftpd

- name: Allow uploads
  lineinfile:
    regexp: '#write_enable=yes'
    line: write_enable=yes
    state: present
  notify: restart vsftpd

- name: Create anonymous FTP directory
  file:
    path: /var/ftp/pub
    state: directory

- name: Copy scoring engine file
  copy:
    src: scoringengine.txt
    dest: /var/ftp/pub/scoringengine.txt